import Pkg
Pkg.add("CSV")
Pkg.add("StatsBase")
Pkg.add("DataFrames")
Pkg.add("DocOpt")
Pkg.add("UMAP")
Pkg.add("RCall")
Pkg.add("MultipleTesting")
Pkg.add("MultivariateStats")
Pkg.add("Distributions")
Pkg.add("CategoricalArrays")
Pkg.add(Pkg.PackageSpec(url = "https://github.com/menchelab/RMP.jl.git"))
Pkg.add("HTTP")
Pkg.add("JSON")
Pkg.add("JLD")
Pkg.add("FreqTables")
Pkg.add("DataStructures")
Pkg.add("BenchmarkTools")
Pkg.add("ParallelDataTransfer")
Pkg.add("Distances")
Pkg.add("LightGraphs")
Pkg.add("SimpleWeightedGraphs")
Pkg.add("GraphIO")
Pkg.add("ParserCombinator")
Pkg.add("Plots")
Pkg.add("GraphRecipes")
