import Pkg
Pkg.add("CSV")
Pkg.add("StatsBase")
Pkg.add("DataFrames")
Pkg.add("UMAP")
Pkg.add("RCall")
Pkg.add("MultipleTesting")
Pkg.add("MultivariateStats")
Pkg.add("Distributions")
Pkg.add(Pkg.PackageSpec(url = "https://github.com/menchelab/RMP.jl.git"))
Pkg.add("DataStructures")
